# Generated by Django 5.0.4 on 2024-04-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=27),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='female', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(default=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.FloatField(default=70),
            preserve_default=False,
        ),
    ]
