# Generated by Django 5.0.4 on 2024-04-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0003_alter_profile_age_alter_workoutresponse_weight_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
