# Generated by Django 5.0.4 on 2024-04-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0004_alter_profile_height_alter_profile_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutresponse',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
